### ISSUE TITLE
mongodb 安装和卸载

### ISSUE THREAD

**Issue by Lenny-Hu** [Lenny-Hu/note#35]
**Mac**
---
- 使用`brew`安装的
```
# 查看mongo是否在启动/启动列表中
launchctl list | grep mongo

# 从启动/启动中删除mongodb
launchctl remove homebrew.mxcl.mongodb

# 停止正在运行的进程
pkill -f mongod

# 用自brew删除mongodb
brew uninstall mongodb
```

**Comment by Lenny-Hu** [comment]
**运行**
---
创建配置文件 mongod.conf
```
systemLog:
  destination: file
  path: /usr/local/var/log/mongodb/mongo.log
  logAppend: true
storage:
  dbPath: /usr/local/var/mongodb
net:
  bindIp: 127.0.0.1
```
启动
```
mongod --config /usr/local/etc/mongod.conf
```
